#!/usr/bin/env bash
# Fix Nginx to run as 'nginx' and listen on port 8080
sudo sed -i 's/^user .*/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
