#!/usr/bin/env bash
# configure my apache file so that when querying the root to return Holberton school

sudo apt-get update
sudo apt-get install apache
sudo /etc/init.d/apache start
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache restart
